### ISSUE TITLE
Convert timesteps to int before running simulation

### ISSUE THREAD

**Issue by BenSchZA** [CADLabs/radCAD#43]
If a user passes a float for timesteps, the simulation should handle this or throw a proper error.

**Comment by alex-damjanovic** [comment]
Is this issue still active?

**Comment by BenSchZA** [comment]
Hey @alex-damjanovic, this has been handled in the `dev` branch, soon to be merged (just need to write up a changelog). See here: https://github.com/CADLabs/radCAD/blob/7710eb61273b94f56d7fe748927e07052010242a/radcad/core.py#L116
