### ISSUE TITLE
No such comm target registered: jupyter.widget.control 

### ISSUE THREAD

**Issue by Dabbrivia** [CADLabs/radCAD#45]
only when using the python3-radcad kernel the following error message appears in jupyter stderr:
```
[I 18:23:38.821 NotebookApp] Kernel started: 6d4a1706-b4c2-4273-91d5-2ae345c56627, name: python3-radcad
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: 1f650824-a671-48d5-97d4-b3c93ce824c4
```
if a vanilla kernel is chosen (ipykernel python3) this error does not appear.

**Comment by Dabbrivia** [comment]
I have tried to fix it using the suggestions https://github.com/jupyter-widgets/ipywidgets/issues/1720 but to no avail.

**Comment by Dabbrivia** [comment]
Hm, I have installed the virtual environment anew and now the same error appears for all kernels. So this seems unrelated to the radcad kernel. I will close this here.

**Comment by Dabbrivia** [comment]
So the culprit seems to be  jupyter-book or some of it's dependencies. 
To reproduce 

```
poetry new testenv
cd testenv
poetry shell
pip install cadCAD radcad cadCAD_tools jupyterlab jupyter-dash
jupyter lab
```
the jupyter lab starts with no error message
```
pip install jupyter-book
jupyter lab
```
now this error appears
```
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: e5c13e62-2a11-4dd5-aafb-979d90f9af26
```
jupyter-book is in the requirements list for the [cadlabs project template](https://github.com/CADLabs/CADLabs-Project-Template/blob/b21c4a5e323283d3501128c656fced00ee75475b/requirements.txt#L16) so maybe this is indeed relevant.

**Comment by BenSchZA** [comment]
Hey @Dabbrivia ! Thanks for detailing the issue here - I'm sure it will prove useful for anyone who has a similar issue. It doesn't seem specific to radCAD, but rather the dependencies and specific development environment as you pointed out.

**Comment by utkonos** [comment]
@Dabbrivia @BenSchZA This isn't related to `jupyter-book` it appears to be related to `ipywidgets`. Unfortunately, someone added a report of this issue to a much older, unrelated issue here:

https://github.com/jupyter-widgets/ipywidgets/issues/2257

It looks like it got the attention of a maintainer, but there hasn't been any activity on that issue for a while after the request for more information. I've provided a step-by-step way to reproduce this error over there.
