### ISSUE TITLE
Is it possible to do a parameter sweep on intital states?

### ISSUE THREAD

**Issue by Dabbrivia** [CADLabs/radCAD#47]
While we can include lists into the parameters for a model and get them iterated over, is something similar possible with initial state(s) of a model?

**Comment by BenSchZA** [comment]
Hey there! One solution is to use a radCAD Experiment, a collection of different Simulations, each with a different initial state. There's currently no way to do this using a method similar to a parameter sweep, but could be a worthwhile addition.
